services:
  apigetweway: 
    container_name: "apigetweway"
    image: ${DOCKER_REGISTRY-}apigetweway
    build:
      context: .
      dockerfile: ApiGetweway/Dockerfile
    ports:
      - "7000:8080"

  catalogservice:
    container_name: "catalogservice"
    image: ${DOCKER_REGISTRY-}catalogservice
    build:
      context: .
      dockerfile: CatalogService/Dockerfile
    ports:
      - "8000:8080"

  orederservice:
    container_name: "orederservice"
    image: ${DOCKER_REGISTRY-}orederservice
    build:
      context: .
      dockerfile: OrederService/Dockerfile
    ports:
      - "9000:8080"
    depends_on:
      - "rabbitmq"

  rabbitmq:
    container_name: "rabbitmq"
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
